development:
  adapter: postgresql
  database: chat_api_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: chat_api_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: chat_api_production
  pool: 5
  timeout: 5000